### ISSUE TITLE
Error loading DualSplash.Core project

### ISSUE THREAD

**Issue by JoseMPersichini** [IssacKramer/Xamarin-forms-Android-Startup-Dual-Splash-Screen#1]
Hello! I want to test this project. I downloaded the soluction and when I open it in VS Community 2017 over Windows 7 x64, the IDE can't load DualSplash.Core project and shows me an error because not found this file:

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props

What is my mistake? Thanks!

**Comment by IssacKramer** [comment]
Hello @Josecanalla .
Thanks for your interest.
Ensure you installed .net Core 1.1 on your machine (better also .net Core 2.0)
and Restore nuget packages (Right click on solution node and click "Restore Packages".
Some people also have trouble to build because of long path name, so if this is the problem , move the whole project to root directory.
Regards!
Issac Kramer.

**Comment by JoseMPersichini** [comment]
@IssacKramer thanks for your reply. I installed this SDK https://github.com/dotnet/core/blob/master/release-notes/download-archives/1.1.4-download.md and this https://www.microsoft.com/net/download/core and then restore NuGet packages but still get the same error.

Also I try to put the solution in C:\ but get same error.

**Comment by JoseMPersichini** [comment]
The SDK installed under C:\Program Files\dotnet\sdk\<version>\Sdks\Microsoft.NET.Sdk and the IDE search it under C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\Sdks\Microsoft.NET.Sdk

**Comment by IssacKramer** [comment]
Don't know exactly what to tell you.
Try to build and deploy other Xamarin Forms Core project of .netstandard : 
[https://github.com/xamarin/xamarin-forms-samples](https://github.com/xamarin/xamarin-forms-samples)
and see if it's ok.
Update to the latest VS 2017 (better 15.3 than 15.4 which has problems now)
Try to restart your pc after each .net sdk install.
Maybe it's time also to move to Win10 x64 (where all development is happening).
Delete .vs directory under the solution folder.
Hope it will help.

**Comment by JoseMPersichini** [comment]
I have updated VS and now the error says that "Can't found the SDK Microsoft.NET.Sdk" :(

**Comment by IssacKramer** [comment]
Did you succeed on other XF .netstandard projects?

**Comment by JoseMPersichini** [comment]
Yes, it works OK. 

I think the difference is in the .csproj of PCL project. 

The first line for XF netstandard is `<Project DefaultTargets="Build" ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`

And the first line of your project is `<Project Sdk="Microsoft.NET.Sdk">`

**Comment by IssacKramer** [comment]
Glad it's working,
but no, .netstandard is REPLACING PCL,
and it's starting like my project (new format of .csproj of VS2017)

**Comment by JoseMPersichini** [comment]
I mean that the XF netstandard projects work, but the DualSplashScreen still not working :( 

So if I create a new solution with new version of VS 2017 it creates it in new .csproj format?

**Comment by IssacKramer** [comment]
Yes.
But I think you're confusing PCL with .netstandard
if the project is start with the old format , it's PCL (If there is parenthesis near the project node and written there "(Portable)" it's and old PCL.
Try to get new sample project of .netstandard.

**Comment by IssacKramer** [comment]
The new .netstandard project is **without** parenthesis-"Portable"

**Comment by JoseMPersichini** [comment]
Hmmm if I try to create a new solution I get only options to create Cross Platform App and Class Library Xamarin.Forms 

And yes, the projects I try are in the old format because have (Portable) in the name

**Comment by IssacKramer** [comment]
So Read posts abount Xamarin forms with .netstandard cross platform projects.
I believe you have installation problem nothing specific to my project.

**Comment by JoseMPersichini** [comment]
You are right. The solution for the error related with "Microsoft.NET.Sdk" is go to VS Community 2017 installer and install ".NET Core cross-platform development". 

Now the project DualSplash.Core is loaded OK, but get two errors when compile (after do Restore NuGet packages):

- Can't find a part of access path 'C:\...\AndroidStartupDualSplash\DualSplash.Core\Views\SlowPage.xaml;Views\SlowPage.xaml'
- Duplicate "EmbeddedResource" were included. 

Thanks for your help!

**Comment by IssacKramer** [comment]
This is the long path name error i mentioned before.
Move it to C:\

**Comment by JoseMPersichini** [comment]
Is it normal that the first time I open the solution takes more than 30 minutes to load? I re-copy the clean solution under C:\ and open the .sln file and is still loading...

Well, it finished and get the same two errors. The path I put the solution is "C:\DS"

**Comment by IssacKramer** [comment]
First time it needs to download all packages.
Delete .vs folder
delete all bin and obj folders
there is problem now on VS 2017 15.4, try to use VS 2017 Preview 15.4 or VS 2017 15.3 (it's better)
Again, try to load other XF .netstandard projects and see if you can build

**Comment by JoseMPersichini** [comment]
Any of this projects https://github.com/xamarin/xamarin-forms-samples is in .netstandard ?

**Comment by IssacKramer** [comment]
https://github.com/onovotny/SampleXamFormsWithNetStandard

**Comment by JoseMPersichini** [comment]
Project https://github.com/onovotny/SampleXamFormsWithNetStandard builds OK
